import os

from scripts.embedder.embeddings import SentenceEmbedder

os.chdir("/home/tommaso/Repositories/teleRAG/")

def main():
    sentences = ["This action sets the maximum length of the answers generated by the model. Specifying a max length helps you prevent long or irrelevant responses and control costs and time."]
    embedder = SentenceEmbedder('paraphrase-MiniLM-L6-v2')
    embeddings = embedder.encode(sentences)
    print("["+",".join([str(e) for e in embeddings[0]])+"]")

if __name__ == "__main__":
    main()